Grammar   <- NEWLINE* Item (NEWLINE+ Item)* NEWLINE* EOF
Item      <- Comment / Rule
Comment   <- COMMENT_LINE (NEWLINE COMMENT_LINE)*
Rule      <- IDENT ARROW Choice
Choice    <- Sequence (SLASH Sequence)*
Sequence  <- Prefix+
Prefix    <- AMP Prefix / BANG Prefix / Postfix
Postfix   <- Atom (QUESTION / STAR / PLUS)*
Atom      <- CutExpr / LabelExpr / Name / Group
CutExpr   <- CUT PAREN_L Choice PAREN_R
LabelExpr <- LABEL PAREN_L STRING COMMA Choice PAREN_R
Name      <- IDENT
Group     <- PAREN_L Choice PAREN_R
