[package]
name = "rex-typesystem"
description.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
thiserror = { workspace = true }
rex-ast = { path = "../rex-ast", version = "3.9.13" }
rex-parser = { path = "../rex-parser", version = "3.9.13" }
chrono = { workspace = true }
uuid = { workspace = true }
rpds = { workspace = true }
rex-util = { path = "../rex-util", version = "3.9.13" }
serde = { workspace = true }

[lints]
workspace = true

[dev-dependencies]
rex-parser = { path = "../rex-parser", version = "3.9.13" }
serde_json = { workspace = true }
