[package]
name = "rex-wasm"
description.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
futures = { workspace = true }
rex-ast = { path = "../rex-ast", version = "4.0.0" }
rex-engine = { path = "../rex-engine", version = "4.0.0" }
rex-lsp = { path = "../rex-lsp", version = "4.0.0" }
rex-parser = { path = "../rex-parser", version = "4.0.0" }
rex-typesystem = { path = "../rex-typesystem", version = "4.0.0" }
rex-util = { path = "../rex-util", version = "4.0.0" }
serde_json = { workspace = true }
wasm-bindgen = "0.2"

[lints]
workspace = true
