[package]
name = "rex-cli"
description.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
publish = false

[dependencies]
clap = { workspace = true }
futures = { workspace = true }
rand = { workspace = true }
rex = { path = "../rex", version = "4.0.0" }
rex-util = { path = "../rex-util", version = "4.0.0" }
serde_json = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true, features = ["fs", "io-std", "io-util", "macros", "process", "rt-multi-thread", "sync", "time"] }

[lints]
workspace = true
