name: Build Script

on:
  push:
    branches: ["v4"]

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-sh:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install Rust toolchain and wasm target
        run: |
          rustup toolchain install stable --profile minimal
          rustup target add wasm32-unknown-unknown --toolchain stable

      - uses: Swatinem/rust-cache@v2

      - name: Install wasm-bindgen CLI
        run: cargo install wasm-bindgen-cli --version 0.2.106

      - name: Install mdBook
        run: cargo install mdbook --locked

      - name: Run build.sh
        run: ./build.sh
