#![allow(unused_variables)]
#![allow(dead_code)]
#![allow(unused_mut)]
#![allow(unused_assignments)]
#![allow(unused_imports)]
#![allow(unused_macros)]
#![allow(non_upper_case_globals)]

use ouroboros::alias::Alias;
use ouroboros::field::{Fields, NamedField, NamedFields, UnnamedField, UnnamedFields};
use ouroboros::generic::Generic;
use ouroboros::product::{Array, Func, Record, RecordDocs, RecordFieldDocs, Tuple};
use ouroboros::ptr::Ptr;
use ouroboros::sum::{Enum, EnumVariant, Fallible, Optional, Union, UnionVariant};
use ouroboros::symbolic::Symbolic;
use ouroboros::type_info::Type as OuroborosType;
use rex::{
    RexType,
    TypeSystem,
    // ADT,
    // ADTVariant,
    // AppliedType,
    // EnumPatch,
    // JsonOptions,
    // Type as rex::Type,
    // TypeCon,
    // TypeVarSupply,
    sym,
};
use std::{
    collections::{BTreeMap, HashMap},
    sync::Arc,
};

#[derive(Default)]
pub struct JsonOptions;

// Note: We cannot use From/Into here as these only work if the types
// they are implemented on are defined in the same crate

pub fn ouroboros_to_rex(
    ts: &mut TypeSystem,
    our_type: &OuroborosType,
    opts: &JsonOptions,
) -> Result<rex::Type, String> {
    match our_type {
        OuroborosType::Unit => Ok(<()>::rex_type()),
        OuroborosType::Bool => Ok(bool::rex_type()),
        OuroborosType::I8 => Ok(i8::rex_type()),
        OuroborosType::I16 => Ok(i16::rex_type()),
        OuroborosType::I32 => Ok(i32::rex_type()),
        OuroborosType::I64 => Ok(i64::rex_type()),
        OuroborosType::I128 => Err("Unsupported ouroboros type: I128".to_string()),
        OuroborosType::U8 => Ok(u8::rex_type()),
        OuroborosType::U16 => Ok(u16::rex_type()),
        OuroborosType::U32 => Ok(u32::rex_type()),
        OuroborosType::U64 => Ok(u64::rex_type()),
        OuroborosType::U128 => Err("Unsupported ouroboros type: U128".to_string()),
        OuroborosType::F32 => Ok(f32::rex_type()),
        OuroborosType::F64 => Ok(f64::rex_type()),
        OuroborosType::String => Ok(String::rex_type()),
        OuroborosType::Array(a) => Ok(rex::Type::array(ouroboros_to_rex(ts, &a.t, opts)?)),
        OuroborosType::Record(r) => {
            todo!()
            // let t_docs: Option<BTreeMap<String, String>> = match &r.doc {
            //     Some(rdocs) => match &rdocs.fields {
            //         Some(RecordFieldDocs::Named(named)) => {
            //             if !named.is_empty() {
            //                 Some(BTreeMap::from_iter(named.clone()))
            //             } else {
            //                 None
            //             }
            //         }
            //         Some(RecordFieldDocs::Unnamed(_)) => None,
            //         None => None,
            //     },
            //     None => None,
            // };

            // Ok(Arc::new(rex::Type::ADT(ADT {
            //     name: r.n.clone(),
            //     variants: vec![ADTVariant {
            //         name: r.n.clone(),
            //         t: Some(fields_to_rex(&r.fields, opts)?),
            //         docs: None,
            //         t_docs,
            //         discriminant: None,
            //     }],
            //     docs: None, // Not generated by #[derive(TypeInfo)]
            // })))
        }
        OuroborosType::Tuple(tuple) => unnamed_fields_to_rex(ts, &tuple.fields, opts),
        OuroborosType::Func(func) => Ok(rex::Type::fun(
            ouroboros_to_rex(ts, &func.a, opts)?,
            ouroboros_to_rex(ts, &func.b, opts)?,
        )),
        OuroborosType::Enum(e) => {
            todo!()
            // let patches = opts.int_enums.get(&e.n);
            // Ok(Arc::new(rex::Type::ADT(ADT {
            //     name: e.n.clone(),
            //     variants: e
            //         .variants
            //         .iter()
            //         .map(|v| ADTVariant {
            //             name: v.n.clone(),
            //             t: None,
            //             docs: None,
            //             t_docs: None,
            //             discriminant: get_discriminant(v, patches),
            //         })
            //         .collect::<Vec<_>>(),
            //     docs: None, // Not generated by #[derive(TypeInfo)]
            // })))
        }
        OuroborosType::Fallible(f) => Ok(rex::Type::result(
            ouroboros_to_rex(ts, &f.err, opts)?,
            ouroboros_to_rex(ts, &f.ok, opts)?,
        )),
        OuroborosType::Optional(o) => Ok(rex::Type::option(ouroboros_to_rex(ts, &o.t, opts)?)),
        OuroborosType::Union(u) => {
            todo!()
            // let mut variants: Vec<ADTVariant> = Vec::new();
            // for v in u.variants.iter() {
            //     variants.push(ADTVariant {
            //         name: v.n.clone(),
            //         t: match &v.fields {
            //             Some(Fields::Named(fields)) => Some(named_fields_to_rex(fields, opts)?),
            //             Some(Fields::Unnamed(fields)) => match fields.fields.len() {
            //                 0 => None,
            //                 1 => Some(ouroboros_to_rex(ts, &fields.fields[0].t, opts)?),
            //                 _ => Some(unnamed_fields_to_rex(fields, opts)?),
            //             },
            //             None => None,
            //         },
            //         docs: None,
            //         t_docs: None,
            //         discriminant: None,
            //     });
            // }

            // Ok(Arc::new(rex::Type::ADT(ADT {
            //     name: u.n.clone(),
            //     variants,
            //     docs: None,
            // })))
        }
        OuroborosType::Ptr(ptr) => {
            todo!()
            // Ok(Arc::new(rex::Type::ADT(ADT {
            //     name: "Ptr".to_string(),
            //     docs: None,
            //     variants: vec![ADTVariant {
            //         name: "Ptr".to_string(),
            //         t: Some(ouroboros_to_rex(ts, &ptr.t, opts)?),
            //         docs: None,
            //         t_docs: None,
            //         discriminant: None,
            //     }],
            // })))
        }
        OuroborosType::Symbolic(symbolic) => {
            todo!()
            // Ok(Arc::new(rex::Type::ADT(ADT {
            //     name: symbolic.n.to_string(),
            //     docs: symbolic.doc.as_ref().map(|d| d.to_string()),
            //     variants: vec![ADTVariant {
            //         name: symbolic.n.clone(),
            //         t: None,
            //         docs: None,
            //         t_docs: None,
            //         discriminant: None,
            //     }],
            // })))
        }
        OuroborosType::Generic(g) => Ok(rex::Type::var(ts.supply.fresh(Some(g.n.clone().into())))),
        OuroborosType::Alias(alias) => ouroboros_to_rex(ts, &alias.t, opts),
    }
}

fn fields_to_rex(
    ts: &mut TypeSystem,
    fields: &Fields,
    opts: &JsonOptions,
) -> Result<rex::Type, String> {
    match fields {
        Fields::Named(named) => named_fields_to_rex(ts, named, opts),
        Fields::Unnamed(unnamed) => unnamed_fields_to_rex(ts, unnamed, opts),
    }
}

fn named_fields_to_rex(
    ts: &mut TypeSystem,
    fields: &NamedFields,
    opts: &JsonOptions,
) -> Result<rex::Type, String> {
    todo!()
    // let mut entries: BTreeMap<String, Arc<rex::Type>> = BTreeMap::new();
    // for field in fields.fields.iter() {
    //     entries.insert(field.n.clone(), ouroboros_to_rex(ts, &field.t, opts)?);
    // }
    // Ok(Arc::new(rex::Type::Dict(entries)))
}

fn unnamed_fields_to_rex(
    ts: &mut TypeSystem,
    fields: &UnnamedFields,
    opts: &JsonOptions,
) -> Result<rex::Type, String> {
    let mut rex_types: Vec<rex::Type> = Vec::new();
    for field in fields.iter() {
        rex_types.push(ouroboros_to_rex(ts, &field.t, opts)?);
    }
    Ok(rex::Type::tuple(rex_types))
}

// fn get_discriminant(v: &EnumVariant, patches: Option<&Vec<EnumPatch>>) -> Option<i64> {
//     let mut discriminant: Option<i64> = None;

//     if let Some(patches) = patches {
//         for p in patches.iter() {
//             if p.enum_name == v.n {
//                 discriminant = Some(p.discriminant);
//             }
//         }
//     }

//     if discriminant.is_none()
//         && let Some(d) = v.v {
//             discriminant = Some(d.into());
//         }
//     discriminant
// }

// fn rex_to_fields(rex_type: &rex::Type) -> Result<Fields, String> {
//     match rex_type {
//         rex::Type::Tuple(rex_types) => {
//             let mut our_fields: Vec<UnnamedField> = Vec::new();
//             for t in rex_types.iter() {
//                 our_fields.push(UnnamedField {
//                     t: rex_to_ouroboros(t)?,
//                 });
//             }
//             Ok(Fields::Unnamed(UnnamedFields { fields: our_fields }))
//         }
//         rex::Type::Dict(entries) => {
//             let mut our_fields: Vec<NamedField> = Vec::new();
//             for (k, t) in entries.iter() {
//                 our_fields.push(NamedField {
//                     n: k.clone(),
//                     t: rex_to_ouroboros(t)?,
//                 });
//             }
//             Ok(Fields::Named(NamedFields { fields: our_fields }))
//         }
//         _ => Ok(Fields::Unnamed(UnnamedFields {
//             fields: vec![UnnamedField {
//                 t: rex_to_ouroboros(rex_type)?,
//             }],
//         })),
//     }
// }

pub fn rex_to_ouroboros(rex_type: &rex::Type) -> Result<OuroborosType, String> {
    todo!()
    // match rex_type {
    //     rex::Type::UnresolvedVar(name) => Ok(OuroborosType::Generic(Generic::new(name))),
    //     rex::Type::Var(_) => Err("Unsupported Rex type: Var".to_string()),
    //     rex::Type::ADT(adt) => rex_adt_to_ouroboros(adt),
    //     rex::Type::App(_, _) => match rex_type.as_applied_type() {
    //         Some(AppliedType::Arrow(a, b)) => Ok(OuroborosType::Func(Func {
    //             a: Box::new(rex_to_ouroboros(a)?),
    //             b: Box::new(rex_to_ouroboros(b)?),
    //         })),
    //         Some(AppliedType::Result(err, ok)) => Ok(OuroborosType::Fallible(Fallible {
    //             ok: Box::new(rex_to_ouroboros(ok)?),
    //             err: Box::new(rex_to_ouroboros(err)?),
    //         })),
    //         Some(AppliedType::Option(t)) => Ok(OuroborosType::Optional(Optional {
    //             t: Box::new(rex_to_ouroboros(t)?),
    //         })),
    //         Some(AppliedType::Promise(_)) => Err("Unsupported Rex type: Promise".to_string()),
    //         Some(AppliedType::List(t)) => {
    //             Ok(OuroborosType::Array(Array::new(rex_to_ouroboros(t)?)))
    //         }
    //         None => Err("Unsupported Rex type: Unknown App".to_string()),
    //     },
    //     rex::Type::Dict(_) => Err("Unsupported Rex type: Dict".to_string()),
    //     rex::Type::Tuple(ts) => {
    //         if ts.is_empty() {
    //             Ok(OuroborosType::Unit)
    //         } else {
    //             let mut fields: Vec<UnnamedField> = Vec::new();
    //             for t in ts.iter() {
    //                 fields.push(UnnamedField::new(rex_to_ouroboros(t)?));
    //             }
    //             Ok(OuroborosType::Tuple(Tuple {
    //                 fields: UnnamedFields { fields },
    //             }))
    //         }
    //     }
    //     rex::Type::Con(TypeCon::Arrow) => Err("Unsupported Rex type: Arrow".to_string()),
    //     rex::Type::Con(TypeCon::Result) => Err("Unsupported Rex type: Result".to_string()),
    //     rex::Type::Con(TypeCon::Option) => Err("Unsupported Rex type: Option".to_string()),
    //     rex::Type::Con(TypeCon::Promise) => Err("Unsupported Rex type: Promise".to_string()),
    //     rex::Type::Con(TypeCon::List) => Err("Unsupported Rex type: List".to_string()),
    //     rex::Type::Con(TypeCon::Bool) => Ok(OuroborosType::Bool),
    //     rex::Type::Con(TypeCon::Uint) => Ok(OuroborosType::U64),
    //     rex::Type::Con(TypeCon::Int) => Ok(OuroborosType::I64),
    //     rex::Type::Con(TypeCon::Float) => Ok(OuroborosType::F64),
    //     rex::Type::Con(TypeCon::String) => Ok(OuroborosType::String),
    //     rex::Type::Con(TypeCon::Uuid) => Err("Unsupported Rex type: Uuid".to_string()),
    //     rex::Type::Con(TypeCon::DateTime) => Err("Unsupported Rex type: DateTime".to_string()),
    // }
}

// fn rex_adt_to_ouroboros(adt: &ADT) -> Result<OuroborosType, String> {
//     if adt.variants.len() == 1 {
//         match adt.variants[0].t.as_deref() {
//             // ADT with a single variant whose type is a dict -> Record w/named fields
//             Some(rex::Type::Dict(entries)) => {
//                 return rex_record_to_ouroboros(&adt.name, &adt.variants[0].t_docs, entries);
//             }
//             // ADT with a single variant whose type is a tuple -> Record w/unnamed fields
//             Some(rex::Type::Tuple(entries)) => {
//                 let mut fields: Vec<UnnamedField> = Vec::new();
//                 for entry in entries.iter() {
//                     fields.push(UnnamedField {
//                         t: rex_to_ouroboros(entry)?,
//                     });
//                 }
//                 return Ok(OuroborosType::Record(Record {
//                     doc: None,
//                     n: adt.name.clone(),
//                     fields: Fields::Unnamed(UnnamedFields { fields }),
//                 }));
//             }
//             // ADT with a single variant of another type -> Alias
//             Some(t) => {
//                 if adt.name == "Ptr" && adt.variants[0].name == "Ptr" {
//                     return Ok(OuroborosType::Ptr(Ptr {
//                         t: Box::new(rex_to_ouroboros(t)?),
//                     }));
//                 }

//                 return Ok(OuroborosType::Alias(Alias {
//                     n: adt.name.clone(),
//                     t: Box::new(rex_to_ouroboros(t)?),
//                 }));
//             }
//             None => {
//                 if adt.variants[0].name == adt.name {
//                     return Ok(OuroborosType::Symbolic(Symbolic {
//                         n: adt.name.clone(),
//                         doc: adt.docs.clone(),
//                     }));
//                 }
//             }
//         }
//     }

//     // ADT where no member carries any data value -> Enum
//     if adt.variants.iter().all(|v| v.t.is_none()) {
//         return rex_enum_to_ouroboros(&adt.name, &adt.variants);
//     }

//     // General ADT
//     let mut our_variants: Vec<UnionVariant> = Vec::new();
//     for rex_variant in adt.variants.iter() {
//         let fields: Option<Fields> = match &rex_variant.t {
//             Some(rex_fields) => Some(rex_to_fields(rex_fields)?),
//             None => None,
//         };
//         our_variants.push(UnionVariant {
//             n: rex_variant.name.clone(),
//             fields,
//         })
//     }
//     let union_ = Union {
//         doc: None,
//         n: adt.name.clone(),
//         variants: our_variants,
//     };
//     Ok(OuroborosType::Union(union_))
// }

// fn rex_record_to_ouroboros(
//     name: &str,
//     t_docs: &Option<BTreeMap<String, String>>,
//     entries: &BTreeMap<String, Arc<rex::Type>>,
// ) -> Result<OuroborosType, String> {
//     // Match behaviour of #[derive(TypeInfo)] - use empty hashmap for field docs if
//     // there are no actual docs present
//     let hm: HashMap<String, String> = match t_docs {
//         Some(entries) => HashMap::from_iter(entries.clone()),
//         None => HashMap::new(),
//     };
//     let doc: Option<RecordDocs> = Some(RecordDocs {
//         record: None,
//         fields: Some(RecordFieldDocs::Named(hm)),
//     });

//     let mut fields: Vec<NamedField> = Vec::new();
//     for (k, v) in entries.iter() {
//         fields.push(NamedField {
//             n: k.clone(),
//             t: rex_to_ouroboros(v)?,
//         });
//     }

//     Ok(OuroborosType::Record(Record {
//         doc,
//         n: name.to_string(),
//         fields: Fields::Named(NamedFields { fields }),
//     }))
// }

// fn rex_enum_to_ouroboros(name: &str, variants: &[ADTVariant]) -> Result<OuroborosType, String> {
//     Ok(OuroborosType::Enum(Enum {
//         doc: None,
//         n: name.to_string(),
//         variants: variants
//             .iter()
//             .map(|v| EnumVariant {
//                 n: v.name.clone(),
//                 v: None,
//             })
//             .collect(),
//     }))
// }

#[cfg(test)]
pub mod test {
    #![allow(dead_code)]
    use super::*;
    use ouroboros::{ptr::Ptr as OuroborosPtr, type_info::TypeInfo};
    use ouroboros_proc_macro::*;
    use rex::{Rex, RexType};
    // use rex_type_system::types as rex;

    #[test]
    fn test_unit() {
        let mut ts = TypeSystem::new();
        assert_eq!(
            ouroboros_to_rex(&mut ts, &OuroborosType::Unit, &Default::default()).unwrap(),
            rex::Type::tuple(vec![])
        );
        assert_eq!(
            rex_to_ouroboros(&rex::Type::tuple(vec![])).unwrap(),
            OuroborosType::Unit
        )
    }

    #[test]
    fn test_tuple1() {
        let our_type = OuroborosType::Tuple(Tuple {
            fields: UnnamedFields {
                fields: vec![UnnamedField {
                    t: OuroborosType::U64,
                }],
            },
        });
        let mut ts = TypeSystem::new();
        let rex_type = ouroboros_to_rex(&mut ts, &our_type, &Default::default()).unwrap();
        assert_eq!(rex_type, rex::Type::tuple(vec![rex::Type::con("u64", 0)]));
        assert_eq!(rex_to_ouroboros(&rex_type).unwrap(), our_type);
    }

    #[test]
    fn test_tuple2() {
        let our_type = OuroborosType::Tuple(Tuple {
            fields: UnnamedFields {
                fields: vec![
                    UnnamedField {
                        t: OuroborosType::U64,
                    },
                    UnnamedField {
                        t: OuroborosType::String,
                    },
                ],
            },
        });
        let mut ts = TypeSystem::new();
        let rex_type = ouroboros_to_rex(&mut ts, &our_type, &Default::default()).unwrap();
        assert_eq!(
            rex_type,
            rex::Type::tuple(vec![rex::Type::con("u64", 0), rex::Type::con("string", 0)])
        );
        assert_eq!(rex_to_ouroboros(&rex_type).unwrap(), our_type);
    }

    #[test]
    fn test_record_named() {
        #[derive(Rex, TypeInfo)]
        struct Foo {
            /// First field
            a: u64,
            /// Second field
            b: String,
        }

        let mut ts = TypeSystem::new();
        assert_eq!(
            ouroboros_to_rex(&mut ts, &Foo::t(), &Default::default()).unwrap(),
            Foo::rex_type()
        );
        assert_eq!(rex_to_ouroboros(&Foo::rex_type()).unwrap(), Foo::t())
    }

    #[test]
    fn test_record_unnamed() {
        #[derive(Rex, TypeInfo)]
        pub struct Foo(pub u64, pub String);

        let mut ts = TypeSystem::new();
        assert_eq!(
            ouroboros_to_rex(&mut ts, &Foo::t(), &Default::default()).unwrap(),
            Foo::rex_type()
        );
        assert_eq!(rex_to_ouroboros(&Foo::rex_type()).unwrap(), Foo::t())
    }

    #[test]
    fn test_enum() {
        #[derive(Rex, TypeInfo)]
        enum Foo {
            One,
            Two,
        }

        let mut ts = TypeSystem::new();
        assert_eq!(
            ouroboros_to_rex(&mut ts, &Foo::t(), &Default::default()).unwrap(),
            Foo::rex_type()
        );
        assert_eq!(rex_to_ouroboros(&Foo::rex_type()).unwrap(), Foo::t());
    }

    #[test]
    fn test_enum_int() {
        mod int {
            use ouroboros_proc_macro::*;
            use rex::Rex;

            #[derive(Rex, TypeInfo)]
            pub enum Foo {
                One = 1,
                Two = 2,
                Three = 3,
            }
        }

        mod plain {
            use ouroboros_proc_macro::*;
            use rex::Rex;

            #[derive(Rex, TypeInfo)]
            pub enum Foo {
                One,
                Two,
                Three,
            }
        }

        // Rex's ADTVariant doesn't keep track of the integer values associated with enum
        // variants. So when we convert back to the ouroboros type, we'll get the same result
        // as derive(TypeInfo) would produce if there were no integer values in the enum.
        let mut ts = TypeSystem::new();
        assert_eq!(
            ouroboros_to_rex(&mut ts, &int::Foo::t(), &Default::default()).unwrap(),
            int::Foo::rex_type()
        );
        assert_eq!(
            rex_to_ouroboros(&int::Foo::rex_type()).unwrap(),
            plain::Foo::t()
        );
    }

    #[test]
    fn test_union_single_field() {
        #[derive(Rex, TypeInfo)]
        enum Foo {
            One(u64),
            Two(String),
        }

        let mut ts = TypeSystem::new();
        assert_eq!(
            ouroboros_to_rex(&mut ts, &Foo::t(), &Default::default()).unwrap(),
            Foo::rex_type()
        );
        assert_eq!(rex_to_ouroboros(&Foo::rex_type()).unwrap(), Foo::t());
    }

    #[test]
    fn test_union_multiple_fields() {
        #[derive(Rex, TypeInfo)]
        enum Foo {
            One(u64, bool),
            Two(String, f64),
        }

        let mut ts = TypeSystem::new();
        assert_eq!(
            ouroboros_to_rex(&mut ts, &Foo::t(), &Default::default()).unwrap(),
            Foo::rex_type()
        );
        assert_eq!(rex_to_ouroboros(&Foo::rex_type()).unwrap(), Foo::t());
    }

    #[test]
    fn test_union_mixed() {
        #[derive(Rex, TypeInfo)]
        enum Foo {
            One,
            Two(u64),
            Three(String, f64),
        }

        let mut ts = TypeSystem::new();
        assert_eq!(
            ouroboros_to_rex(&mut ts, &Foo::t(), &Default::default()).unwrap(),
            Foo::rex_type()
        );
        assert_eq!(rex_to_ouroboros(&Foo::rex_type()).unwrap(), Foo::t());
    }

    #[test]
    fn test_union_named() {
        #[derive(Rex, TypeInfo)]
        enum Foo {
            One { a: u64, b: String },
            Two { a: f64, b: bool },
        }

        let mut ts = TypeSystem::new();
        assert_eq!(
            ouroboros_to_rex(&mut ts, &Foo::t(), &Default::default()).unwrap(),
            Foo::rex_type()
        );
        assert_eq!(rex_to_ouroboros(&Foo::rex_type()).unwrap(), Foo::t());
    }

    #[test]
    fn test_numeric_roundtrip() {
        // Rex only supports 64-bit numeric types (Uint, Int, Float). Converting from ouroboros
        // types to rex again will therefore result in only the 64-bit variants being present.
        // TODO(rex4): Rex now actually supports all numeric tyypes so it should be fine
        mod different_sizes {
            use ouroboros_proc_macro::*;
            use rex::Rex;

            #[derive(Rex, TypeInfo)]
            pub struct Foo {
                pub u1: u8,
                pub u2: u16,
                pub u3: u32,
                pub u4: u64,
                pub i1: i8,
                pub i2: i16,
                pub i3: i32,
                pub i4: i64,
                pub f1: f32,
                pub f2: f64,
            }
        }

        mod all_64 {
            use ouroboros_proc_macro::*;
            use rex::Rex;

            #[derive(Rex, TypeInfo)]
            pub struct Foo {
                pub u1: u64,
                pub u2: u64,
                pub u3: u64,
                pub u4: u64,
                pub i1: i64,
                pub i2: i64,
                pub i3: i64,
                pub i4: i64,
                pub f1: f64,
                pub f2: f64,
            }
        }

        let mut ts = TypeSystem::new();
        assert_eq!(
            rex_to_ouroboros(
                &ouroboros_to_rex(&mut ts, &different_sizes::Foo::t(), &Default::default())
                    .unwrap()
            )
            .unwrap(),
            all_64::Foo::t()
        );

        assert_eq!(
            ouroboros_to_rex(&mut ts, &different_sizes::Foo::t(), &Default::default()).unwrap(),
            all_64::Foo::rex_type()
        );
    }

    #[test]
    fn test_alias() {
        let our_type = OuroborosType::Alias(Alias {
            n: "Foo".to_string(),
            t: Box::new(OuroborosType::U64),
        });

        let mut ts = TypeSystem::new();
        assert_eq!(
            ouroboros_to_rex(&mut ts, &our_type, &Default::default()).unwrap(),
            rex::Type::con("u64", 0)
        );
    }

    #[test]
    fn test_symbolic_doc() {
        #[derive(Rex, TypeInfo)]
        /// Test
        pub enum Foo {
            Foo,
        }

        let our_type = OuroborosType::Symbolic(Symbolic {
            n: "Foo".to_string(),
            doc: Some("Test".to_string()),
        });
        let rex_type = Foo::rex_type();

        let mut ts = TypeSystem::new();
        assert_eq!(
            ouroboros_to_rex(&mut ts, &our_type, &Default::default()).unwrap(),
            rex_type
        );
        assert_eq!(rex_to_ouroboros(&rex_type).unwrap(), our_type);
    }

    #[test]
    fn test_symbolic_nodoc() {
        #[derive(Rex, TypeInfo)]
        pub enum Foo {
            Foo,
        }

        let our_type = OuroborosType::Symbolic(Symbolic {
            n: "Foo".to_string(),
            doc: None,
        });
        let rex_type = Foo::rex_type();

        let mut ts = TypeSystem::new();
        assert_eq!(
            ouroboros_to_rex(&mut ts, &our_type, &Default::default()).unwrap(),
            rex_type
        );
        assert_eq!(rex_to_ouroboros(&rex_type).unwrap(), our_type);
    }

    #[test]
    fn test_ptr() {
        #[derive(Rex)]
        pub enum Ptr {
            Ptr(String),
        }

        let our_type = OuroborosType::Ptr(OuroborosPtr {
            t: Box::new(OuroborosType::String),
        });
        let rex_type = Ptr::rex_type();
        let mut ts = TypeSystem::new();
        assert_eq!(
            ouroboros_to_rex(&mut ts, &our_type, &Default::default()).unwrap(),
            rex_type
        );
        assert_eq!(rex_to_ouroboros(&rex_type).unwrap(), our_type);
    }

    #[test]
    fn test_func() {
        let our_type = OuroborosType::Func(Func {
            a: Box::new(OuroborosType::U64),
            b: Box::new(OuroborosType::String),
        });
        let rex_type = rex::Type::fun(rex::Type::con("u64", 0), rex::Type::con("string", 0));

        let mut ts = TypeSystem::new();
        assert_eq!(
            ouroboros_to_rex(&mut ts, &our_type, &Default::default()).unwrap(),
            rex_type
        );
        assert_eq!(rex_to_ouroboros(&rex_type).unwrap(), our_type);
    }

    #[test]
    fn test_fallible() {
        #[derive(Rex, TypeInfo)]
        pub struct Foo {
            pub a: Result<u64, String>,
        }

        let mut ts = TypeSystem::new();
        assert_eq!(
            ouroboros_to_rex(&mut ts, &Foo::t(), &Default::default()).unwrap(),
            Foo::rex_type()
        );
        assert_eq!(rex_to_ouroboros(&Foo::rex_type()).unwrap(), Foo::t());
    }

    #[test]
    fn test_generic() {
        let mut ts = TypeSystem::new();
        let tv = ts.supply.fresh(Some(sym("T")));
        let our_generic = OuroborosType::Generic(Generic::new("T"));
        let rex_generic = rex::Type::var(tv.clone());
        let mut ts = TypeSystem::new();
        assert_eq!(
            ouroboros_to_rex(&mut ts, &our_generic, &Default::default()).unwrap(),
            rex_generic
        );
        assert_eq!(rex_to_ouroboros(&rex_generic).unwrap(), our_generic);
    }
}
